//Подключить эти функции для проверки переводов

testDef1 : function
{
  printf(VERSION_NUM);
printf(IDS_VERSION_FMT);
printf(IDS_HELP_TEXT);
printf(IDS_CREDITS_TEXT);
printf(IDS_ENDINGS);
printf(IDS_FOUND_ENDINGS);
printf(IDS_INTRO);
printf(IDS_ME_LDESC);

printf(IDS_WAIT_DEFAULT);
printf(IDS_JUMP_DEFAULT);
printf(IDS_DIG_DEFAULT);
printf(IDS_YELL_DEFAULT);
printf(IDS_WALL_DEFAULT);
printf(IDS_FLOOR_DEFAULT);
printf(IDS_FLOOR_SIT);
printf(IDS_CEILING_DEFAULT);
printf(IDS_LISTEN_DEFAULT);

printf(IDS_HALAT_DESC);

// STARTROOM
printf(IDS_STARTROOM_LDESC);
printf(IDS_STARTROOM_WAIT);
printf(IDS_STARTROOM_NOEXIT);
printf(IDS_STARTROOM_JUMP);
printf(IDS_STARTROOM_DIG);
printf(IDS_STARTROOM_HIT);
printf(IDS_STARTROOM_TALK);
printf(IDS_STARTROOM_CLEAN);
printf(IDS_STARTROOM_SEARCH);

// STARTBED
printf(IDS_STARTBED_LDESC);
printf(IDS_STARTBED_TALK);
printf(IDS_STARTBED_MOVE);
printf(IDS_STARTBED_TAKE);
printf(IDS_STARTBED_DROP);
printf(IDS_STARTBED_WEAR);
printf(IDS_STARTBED_READ);
printf(IDS_STARTBED_TURN);
printf(IDS_STARTBED_TURNON);
printf(IDS_STARTBED_TURNOFF);
printf(IDS_STARTBED_SCREW);
printf(IDS_STARTBED_UNSCREW);
printf(IDS_STARTBED_EAT);
printf(IDS_STARTBED_CLEAN);
printf(IDS_STARTBED_BREAK);
printf(IDS_STARTBED_SEARCH);
printf(IDS_STARTBED_LISTENTO);
printf(IDS_STARTBED_SMELL);
printf(IDS_STARTBED_TOUCH);

// coridorroom
printf(IDS_CORID_LDESC);
printf(IDS_CORID_WAIT);
printf(IDS_CORID_NOEXIT);
printf(IDS_CORID_JUMP);
printf(IDS_CORID_DIG);
printf(IDS_CORID_HIT);
printf(IDS_CORID_TALKDESC);
printf(IDS_CORID_CLEAN);
printf(IDS_CORID_SEARCH);

// techsection
printf(IDS_TECH_LDESC);
printf(IDS_TECH_WAIT);
printf(IDS_TECH_NOEXIT);
printf(IDS_TECH_JUMP);
printf(IDS_TECH_DIG);
printf(IDS_TECH_HIT);
printf(IDS_TECH_TALKDESC);
printf(IDS_TECH_CLEAN);
printf(IDS_TECH_SEARCH);
printf(IDS_TECH_YELL);

// kabel
printf(IDS_KABEL_LDESC);
printf(IDS_KABEL_TALK);
printf(IDS_KABEL_MOVE);
printf(IDS_KABEL_TAKE);
printf(IDS_KABEL_DROP);
printf(IDS_KABEL_WEAR);
printf(IDS_KABEL_READ);
printf(IDS_KABEL_TURN);
printf(IDS_KABEL_TURNON);
printf(IDS_KABEL_TURNOFF);
printf(IDS_KABEL_SCREW);
printf(IDS_KABEL_UNSCREW);
printf(IDS_KABEL_EAT);
printf(IDS_KABEL_CLEAN);
printf(IDS_KABEL_BREAK);
printf(IDS_KABEL_SEARCH);
printf(IDS_KABEL_LISTENTO);
printf(IDS_KABEL_SMELL);
printf(IDS_KABEL_TOUCH);

// medroom
printf(IDS_MEDROOM_LDESC);
printf(IDS_MEDROOM_WAIT);
printf(IDS_MEDROOM_NOEXIT);
printf(IDS_MEDROOM_JUMP);
printf(IDS_MEDROOM_DIG);
printf(IDS_MEDROOM_HIT);
printf(IDS_MEDROOM_TALKDESC);
printf(IDS_MEDROOM_CLEAN);
printf(IDS_MEDROOM_SEARCH);
printf(IDS_MEDROOM_END);

// robotmed
printf(IDS_MEDROBOT_LDESC);
printf(IDS_MEDROBOT_TALKDESC);
printf(IDS_MEDROBOT_MOVE);
printf(IDS_MEDROBOT_TAKE);
printf(IDS_MEDROBOT_DROP);
printf(IDS_MEDROBOT_WEAR);
printf(IDS_MEDROBOT_READ);
printf(IDS_MEDROBOT_TURN);
printf(IDS_MEDROBOT_TURNON);
printf(IDS_MEDROBOT_TURNOFF);
printf(IDS_MEDROBOT_SCREW);
printf(IDS_MEDROBOT_UNSCREW);
printf(IDS_MEDROBOT_EAT);
printf(IDS_MEDROBOT_CLEAN);
printf(IDS_MEDROBOT_BREAK);
printf(IDS_MEDROBOT_SEARCH);
printf(IDS_MEDROBOT_LISTENTO);
printf(IDS_MEDROBOT_SMELL);
printf(IDS_MEDROBOT_TOUCH);

//coridor run
printf(IDS_RUN_LDESC);
printf(IDS_RUN_WAIT);
printf(IDS_RUN_NOEXIT);
printf(IDS_RUN_JUMP);
printf(IDS_RUN_DIG);
printf(IDS_RUN_NORTH);
printf(IDS_RUN_SOUTH);
printf(IDS_RUN_HIT);
printf(IDS_RUN_TALKDESC);
printf(IDS_RUN_CLEAN);
printf(IDS_RUN_SEARCH);

// anabia
printf(IDS_ANABIA_LDESC);
printf(IDS_ANABIA_WAIT_OUT);
printf(IDS_ANABIA_WAIT_IN);
printf(IDS_ANABIA_NOEXIT);
printf(IDS_ANABIA_JUMP);
printf(IDS_ANABIA_DIG);
printf(IDS_ANABIA_HIT);
printf(IDS_ANABIA_TALKDESC);
printf(IDS_ANABIA_CLEAN);
printf(IDS_ANABIA_SEARCH);

// anabia bed
printf(IDS_ANBED_LDESC);
printf(IDS_ANBED_LIE);
printf(IDS_ANBED_MOVE);
printf(IDS_ANBED_TAKE);
printf(IDS_ANBED_READ);
printf(IDS_ANBED_TURN);
printf(IDS_ANBED_TURNON);
printf(IDS_ANBED_TURNOFF);
printf(IDS_ANBED_SCREW);
printf(IDS_ANBED_UNSCREW);
printf(IDS_ANBED_EAT);
printf(IDS_ANBED_CLEAN);
printf(IDS_ANBED_BREAK);
printf(IDS_ANBED_SEARCH);
printf(IDS_ANBED_LISTENTO);
printf(IDS_ANBED_SMELL);
printf(IDS_ANBED_TOUCH);

//control room
printf(IDS_CROOM_LDESC);
printf(IDS_CROOM_WAIT);
printf(IDS_CROOM_NOEXIT);
printf(IDS_CROOM_JUMP);
printf(IDS_CROOM_DIG);
printf(IDS_CROOM_HIT);

//control panel
printf(IDS_PANEL_LDESC);
printf(IDS_PANEL_TALKDESC);
printf(IDS_PANEL_MOVE);
printf(IDS_PANEL_READ);
printf(IDS_PANEL_TURNON);
printf(IDS_PANEL_EAT);
printf(IDS_PANEL_CLEAN);
printf(IDS_PANEL_BREAK);
printf(IDS_PANEL_LISTENTO);
printf(IDS_PANEL_SMELL);
printf(IDS_PANEL_TOUCH);
printf(IDS_PANEL_BEFORE_BREAK);
printf(IDS_PANEL_BEFORE_BUNT);
printf(IDS_PANEL_AFTER_OUT);

//nest
printf(IDS_NEST_LDESC);
printf(IDS_NEST_WAIT);
printf(IDS_NEST_NOEXIT);
printf(IDS_NEST_JUMP);
printf(IDS_NEST_DIG);
printf(IDS_NEST_HIT);
printf(IDS_NEST_TALKDESC);
printf(IDS_NEST_CLEAN);
printf(IDS_NEST_SEARCH);
printf(IDS_SLIZ_LDESC);

//snail
printf(IDS_SNAIL_LDESC);
printf(IDS_SNAIL_TALKDESC);
printf(IDS_SNAIL_MOVE);
printf(IDS_SNAIL_TAKE);
printf(IDS_SNAIL_DROP);
printf(IDS_SNAIL_WEAR);
printf(IDS_SNAIL_READ);
printf(IDS_SNAIL_TURNONOFF);
printf(IDS_SNAIL_SCREW);
printf(IDS_SNAIL_EAT);
printf(IDS_SNAIL_CLEAN);
printf(IDS_SNAIL_BREAK);
printf(IDS_SNAIL_LISTENTO);
printf(IDS_SNAIL_SMELL);
printf(IDS_SNAIL_TOUCH);

//emitter
printf(IDS_EMITTER_LDESC);
printf(IDS_EMITTER_WAIT);
printf(IDS_EMITTER_NOEXIT);
printf(IDS_EMITTER_JUMP);
printf(IDS_EMITTER_DIG);
printf(IDS_EMITTER_HIT);
printf(IDS_EMITTER_TALKDESC);
printf(IDS_EMITTER_CLEAN);
printf(IDS_EMITTER_SEARCH);

//tele
printf(IDS_TELE_LDESC);
printf(IDS_TELE_MOVE);
printf(IDS_TELE_TAKE);
printf(IDS_TELE_WEAR);
printf(IDS_TELE_READ);
printf(IDS_TELE_TURN);
printf(IDS_TELE_TURNONOFF);
printf(IDS_TELE_SCREW);
printf(IDS_TELE_EAT);
printf(IDS_TELE_LISTENTO);
printf(IDS_TELE_SMELL);
printf(IDS_TELE_TOUCH);

//cargo
printf(IDS_CARGO_LDESC);
printf(IDS_CARGO_WAIT);
printf(IDS_CARGO_NOEXIT);
printf(IDS_CARGO_JUMP);
printf(IDS_CARGO_DIG);
printf(IDS_CARGO_TALKDESC);
printf(IDS_CARGO_CLEAN);
printf(IDS_CARGO_SEARCH);

//eczo
printf(IDS_ECZO_LDESC);
printf(IDS_ECZO_MOVE);
printf(IDS_ECZO_TAKE);
printf(IDS_ECZO_WEAR);
printf(IDS_ECZO_READ);
printf(IDS_ECZO_TURN);
printf(IDS_ECZO_TURNONOFF);
printf(IDS_ECZO_SCREW);
printf(IDS_ECZO_EAT);
}

testDef2 : function
{
printf(IDS_ECZO_LISTENTO);
printf(IDS_ECZO_SMELL);
printf(IDS_ECZO_TOUCH);

//state move
printf(AUTO_MOVE_STARTROOM);
printf(AUTO_MOVE_CORIDOR);
printf(AUTO_MOVE_RUN);
printf(AUTO_MOVE_MED);
printf(AUTO_MOVE_CROOM);
printf(AUTO_MOVE_ANABIA);
printf(AUTO_MOVE_NEST);
printf(AUTO_MOVE_TELE);
printf(AUTO_MOVE_CARGO);



//endings
printf(IDS_DIE_BED);
printf(IDS_DIE_MED);
printf(IDS_DIE_RUN);
printf(IDS_HERO_END);
printf(IDS_DEEP_END);
printf(IDS_BUNT_END);
printf(IDS_STAR_END);
printf(IDS_DIE_WALK);
printf(IDS_DIE_YELL);
printf(IDS_DIE_SLEEP);
printf(IDS_DIE_EAT);
printf(IDS_DIE_TELE);
printf(IDS_DIE_ECZO);

printf(IDS_DIE_BED_HINT);
printf(IDS_DIE_MED_HINT);
printf(IDS_DIE_RUN_HINT);
printf(IDS_HERO_END_HINT);
printf(IDS_DEEP_END_HINT);
printf(IDS_BUNT_END_HINT);
printf(IDS_STAR_END_HINT);
printf(IDS_DIE_WALK_HINT);
printf(IDS_DIE_YELL_HINT);
printf(IDS_DIE_SLEEP_HINT);
printf(IDS_DIE_EAT_HINT);
printf(IDS_DIE_TELE_HINT);
printf(IDS_DIE_ECZO_HINT);

printf(IDS_FMT_NEW_ENDING);
printf(IDS_FMT_OLD_ENDING);
printf(IDS_START_NEW_GAME);

//sea battle
printf(IDS_SPACE_INTRO);
printf(IDS_SPACE_LDESC);
printf(IDS_SPACE_CANMOVE);
printf(IDS_SPACE_START_WARNING);
printf(IDS_SPACE_MY_FLEET);
printf(IDS_SPACE_EN_FLEET);
printf(IDS_SPACE_FL_LDESC);
printf(IDS_SPACE_FI_LDESC);
printf(IDS_SPACE_BO_LDESC);
printf(IDS_SPACE_INV_NUM);

printf(IDS_SPACE_MAP_MOVE_OK);
printf(IDS_SPACE_MAP_MOVE_LOW_EDGE);
printf(IDS_SPACE_MAP_MOVE_HIGH_EDGE);
printf(IDS_SPACE_MAP_MOVE_NOT_FREE);
printf(IDS_SPACE_MAP_MOVE_TOO_CLOSE);
printf(IDS_SPACE_MAP_MOVE_DISALLOW);
printf(IDS_SPACE_MAP_ERR_MOVE);

printf(IDS_SPACE_HIT_RES_LOW_EDGE);
printf(IDS_SPACE_HIT_RES_HIGH_EDGE);
printf(IDS_SPACE_HIT_RES_ALREADY);
printf(IDS_SPACE_HIT_RES_MISS);
printf(IDS_SPACE_HIT_RES_GOT);
printf(IDS_SPACE_HIT_RES_KILL);
printf(IDS_SPACE_EN_HIT_RES_MISS);
printf(IDS_SPACE_EN_HIT_RES_GOT);
printf(IDS_SPACE_EN_HIT_RES_KILL);

printf(IDS_SPACE_VICTORY);
printf(IDS_SPACE_DEFEAT);
printf(IDS_SPACE_FMT_UNKNOWN_STATE);

}